services:
  # Serviço do Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest # A mesma imagem oficial.
    container_name: marmitech-keycloak
    # O comando para iniciar em modo de produção.
    command: start
    # Variáveis de ambiente para configurar o Keycloak.
    environment:
      # Credenciais do administrador inicial do Keycloak.
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # --- Configurações de conexão com o banco de dados MySQL existente ---
      KC_DB: mariadb

      # O endereço (IP ou hostname) onde seu servidor MySQL está rodando.
      KC_DB_URL_HOST: 192.168.3.18 #10.35.239.4 

      # A porta do seu MySQL (o padrão é 3306).
      KC_DB_URL_PORT: 3306

      # O nome do banco de dados que você já criou para o Keycloak.
      KC_DB_URL_DATABASE: keycloakFacul

      # O nome de usuário que tem permissão para acessar esse banco.
      KC_DB_USERNAME: keycloakFacul

      # A senha para o usuário do banco de dados.
      KC_DB_PASSWORD: 123456

      # --- Configurações de Hostname e HTTP ---
      # O Keycloak precisa saber qual é sua URL pública para gerar os links de redirecionamento corretos.
      KC_HOSTNAME: front.marmitech.qzz.io
      # Para desenvolvimento local, desabilitamos a exigência de HTTPS.
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'

    # Mapeia a porta do contêiner para a máquina local.
    ports:
      - "5001:8080"
    # Garante que o contêiner reinicie se falhar.
    restart: unless-stopped
